### ISSUE TITLE
Support for array of urls_file

### ISSUE THREAD

**Issue by nickgeorgiou** [salsadigitalauorg/merlin-framework#113]
**Description**
Add the ability to specify an array of URL files, all containing lists of URLs.

**Proposed solution**
If the urls_file configuration property is provided as a string, treat that as the single file name. Otherwise, if the urls_file is provided as an array, treat each of the array items as a file URI containing a list of URLs.

**Comment by srowlands** [comment]
Done and documented: https://salsadigitalauorg.github.io/merlin-framework/docs/url-options#urls-in-separate-files
