### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jannakha** [salsadigitalauorg/merlin-framework#133]
1. Installation fails:
`composer require salsadigitalauorg/merlin-framework:XXX` fails because package name in composer.json is invalid (`composer require salsadigital/migrate:0.4.1` worked).

- https://github.com/salsadigitalauorg/merlin-framework/blob/develop/composer.json#L2 
- name should match package name, eg github repo name `salsadigitalauorg/merlin-framework`

2.  Invalid path for require-autoload when using composer. Launching ./vendor/bin/merlin or ./vendor/salsadigital/migrage/merlin fails because require autoload fails.
- https://github.com/salsadigitalauorg/merlin-framework/blob/develop/merlin#L12
- should be `require __DIR__ . '/../../../vendor/autoload.php';`

3. Update docs and usage docs:
- https://github.com/salsadigitalauorg/merlin-framework/blame/develop/README.md#L55
- should include command, eg `merlin <command> -c <path/to/config.yml> -o <path/to/output>` like 
`merlin crawl -c settings.yml -o ./output` or `merlin generate -c settings.yml -o ./output` etc

**Comment by stooit** [comment]
Thanks for raising @jannakha - will get a bugfix release out shortly to resolve
