### ISSUE TITLE
When there are redirects to external site, the effective URLs file still saves the external URL as relative

### ISSUE THREAD

**Issue by gargsuchi** [salsadigitalauorg/merlin-framework#138]
**Describe the bug**
When I crawl a site, and I see redirects to an external site - something like this 

url_original: https://4503abd5-06ad-470e-b766-9e7f35f6551c.sites.quantcdn.io/about/key-staff/chief-paramedic-officer
url_effective: https://www.bettersafercare.vic.gov.au/about-us/about-scv/our-leadership-team/adj-assoc-prof-alan-eade-asm

The effective URLs site lists the URL as /about-us/about-scv/our-leadership-team/adj-assoc-prof-alan-eade-asm, even though this URL does not exist on the original site.

**Comment by derklempner** [comment]
This one has been fixed in the `feature/group-type` branch.
